apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watch-all-{{ .Values.version }}
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get", "watch", "list"]
