apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-resources-pods-{{ .Values.version}}
  labels:
    app: watch-resources-pods-{{ .Values.version}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-resources-pods-{{ .Values.version}}
  template:
    metadata:
      labels:
        app: watch-resources-pods-{{ .Values.version}}
    spec:
      serviceAccountName: watch-all 
      containers:
      - name: pods
        image: quay.io/fdavalo/watch-resources:{{ .Values.tag.watch_resources}}
        ports:
        - containerPort: 8080
        args: ['sh', 'start.sh', 'pods', '/var/run/secrets/kubernetes.io/serviceaccount', '/run/ca', '/var/run/secrets/kubernetes.io/serviceaccount']
        volumeMounts:
        - name: ca
          mountPath: '/run/ca'
          readOnly: true
      volumes:
      - name: ca
        secret:
          secretName: ca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-resources-services-{{ .Values.version}}
  labels:
    app: watch-resources-services-{{ .Values.version}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-resources-services-{{ .Values.version}}
  template:
    metadata:
      labels:
        app: watch-resources-services-{{ .Values.version}}
    spec:
      serviceAccountName: watch-all
      containers:
      - name: services
        image: quay.io/fdavalo/watch-resources:{{ .Values.tag.watch_resources}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        args: ['sh', 'start.sh', 'services', '/var/run/secrets/kubernetes.io/serviceaccount', '/run/ca', '/var/run/secrets/kubernetes.io/serviceaccount']
        volumeMounts:
        - name: ca
          mountPath: '/run/ca'
          readOnly: true
      volumes:
      - name: ca 
        secret:
          secretName: ca
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: watch-flows-{{ .Values.version}}
  namespace: {{ .Release.Namespace }}
  labels:
    app: watch-flows-{{ .Values.version}}
spec:
  selector:
    matchLabels:
      app: watch-flows-{{ .Values.version}}
  template:
    metadata:
      labels:
        app: watch-flows-{{ .Values.version}}
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: watch-all
      containers:
      - name: flows 
        image: quay.io/fdavalo/watch-flows-int:{{ .Values.tag.watch_flows_int}}
        env:
        - name: WATCH_PODS_URL 
          value: watch-resources-pods.{{ .Values.wildcard }}
        - name: WATCH_SERVICES_URL
          value: watch-resources-services.{{ .Values.wildcard }}
        ports:
        - containerPort: 8080
        args: ['sh', 'start.sh']
        securityContext:
          privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-topology-web-{{ .Values.version}}
  labels:
    app: net-topology-web-{{ .Values.version}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-topology-web-{{ .Values.version}}
  template:
    metadata:
      labels:
        app: net-topology-web-{{ .Values.version}} 
    spec:
      serviceAccountName: watch-all
      containers:
      - name: web 
        image: quay.io/fdavalo/net-topology-web:{{ .Values.tag.web}}
        ports:
        - containerPort: 8080
        args: ['sh', 'start.sh']
